### ISSUE TITLE
trasigheter när man lägger till inköp på production

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#32]
något verkar försöka trycka in business_unit_id i purchases på production. Det är fel.

Jag deployade nyss en ny version, men det kan vara vettigt att kolla om detta felet kvarstår.

```
ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'business_unit_id' in 'field list': 
INSERT INTO `purchases` 
  (`description`, `workflow_state`, `person_id`, `business_unit_id`, `purchased_at`, `slug`, `created_at`, `updated_at`, `budget_post_id`, `year`) 
VALUES ('Router till Ericsson', 'new', 59, NULL, '2011-10-05', 'temp-slug-2011-11-01 16:38:34 +0000', '2011-11-01 16:38:34', '2011-11-01 16:38:34', 66, 2011)):  
app/controllers/purchases_controller.rb:46:in `block in create'  app/controllers/purchases_controller.rb:45:in `create'
```

**Comment by Frost** [comment]
Såhär tillochmed, så får man med params:

```
Started POST "/inkop" for 213.103.201.54 at 2011-11-01 16:38:34 +0000
  Processing by PurchasesController#create as HTML
  Parameters: {
    "utf8"=>"✓", 
    "authenticity_token"=>"6U6WPtg33UEshuYH0qP35zw+nb35zJrXsh+Vw1tAvfQ=", 
    "purchase"=>{
      "purchased_at"=>"2011-10-05", 
      "budget_post_id"=>"66", 
      "description"=>"Router till Ericsson", 
      "items_attributes"=>{
        "0"=>{"amount"=>"299", "comment"=>"", "product_type_id"=>"29", "_destroy"=>""}
      }
    }, 
    "business_unit"=>"7", 
    "commit"=>"Spara Inköp"
  }
Completed 500 Internal Server Error in 17ms

ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'business_unit_id' in 'field list': 
  INSERT INTO `purchases` 
    (`description`, `workflow_state`, `person_id`, `business_unit_id`, `purchased_at`, `slug`, `created_at`, `updated_at`, `budget_post_id`, `year`) 
  VALUES 
    ('Router till Ericsson', 'new', 59, NULL, '2011-10-05', 'temp-slug-2011-11-01 16:38:34 +0000', '2011-11-01 16:38:34', '2011-11-01 16:38:34', 66, 2011)):
  app/controllers/purchases_controller.rb:46:in `block in create'
  app/controllers/purchases_controller.rb:45:in `create'
```

Vad jag egentligen undrar (och det som är den stora frågan) är var `business_unit_id` kommer från, för det är ju inte från params[:purchase]

**Comment by Frost** [comment]
Det verkade ha att göra med lite underligheter i javascripten, men funkar nu.
